development:
  adapter: postgresql
  database: expense_tracker_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: expense_tracker_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: expense_tracker_production
  pool: 5
  timeout: 5000